//
//  File.swift
//  
//
//  Created by admin on 06.06.2023.
//

import Foundation

struct AppIDs {
    
    static let ALPHA_PREFIX =       "alpha"
    
    static let VS_PREFIX =           "vs"
    static let VS_STOPWATCH_ID =     "vs-0001"
    static let VS_TORCH_ID =         "vs-0002"
    static let VS_PHONE_INFO_ID =    "vs-0003"
    static let VS_PAIRS_ID =         "0000-0000-0000-0004"
    static let VS_DICTIONARY_ID =    "0000-0000-0000-0005"
    static let VS_CLOCK_ID =         "0000-0000-0000-0006"
    static let VS_AGE_PREDICTOR_ID = "0000-0000-0000-0007"
    
    static let JK_PREFIX =           "jk"
    static let JK_ADVICE_ID =        "0000-0000-0000-0008"
    static let JK_MEMENTO_ID =       "0000-0000-0000-0009"
    static let JK_NOTE_ID =          "0000-0000-0000-0010"
    static let JK_RANDOM_NUMBER_ID = "0000-0000-0000-0011"
    
    static let SK_PREFIX =           "sk"
    static let SK_DOODLE_JUMP_ID =   "0000-0000-0000-0012"
    static let SK_INDIAN_NAMES_ID =  "0000-0000-0000-0013"
    static let SK_TETRIS_ID =        "0000-0000-0000-0014"
    static let SK_VEHICLE_QUIZ_ID =  "0000-0000-0000-0015"
    static let SK_WHO_ARE_YOU_ID =   "0000-0000-0000-0016"
    
    static let MB_PREFIX =           "mb"
    static let MB_STOPWATCH =        "mb-0001"
    static let MB_SPEED_TEST =       "mb-0002"
    static let MB_PING_TEST =        "mb-0003"
    static let MB_ALARM =            "mb-0004"
    static let MB_CHECK_IP =         "mb-0012"
    static let MB_LUCKY_NUMBER =     "mb-0005"
    static let MB_SPACE_FIGHTER =    "mb-0010"
    static let MB_RICK_AND_MORTY =   "mb-0013"
    static let MB_NOTES =            "0000-0000-0000-0026"
    static let MB_RECORDER =         "0000-0000-0000-0027"
    static let MB_CATS_GALLERY =     "0000-0000-0000-0028"
    static let MB_BMI_CALC_ID =      "mb-0011"
    static let MB_TIC_TAC_TOE =      "0000-0000-0000-0030"
    static let MB_WEATHER =          "0000-0000-0000-0031"
    static let MB_NOTEBOOK =         "0000-0000-0000-0032"
    static let MB_QR =               "0000-0000-0000-0033"
    static let MB_TIMER =            "0000-0000-0000-0034"
    static let MB_CAMERA =           "0000-0000-0000-0035"
    static let MB_CATCHER =          "mb-0006"
    static let MB_CLICKER =          "0000-0000-0000-0037"
    static let MB_FACTS =            "mb-0007"
    static let MB_RACE =             "mb-0008"
    static let MB_TORCH =            "mb-0009"
    static let MB_PASS_GEN =         "mb-0014"
    static let MB_DEVICE_INFO =      "mb-0015"
    static let MB_HASH_GEN =         "mb-0016"
    static let MB_SERIALS =          "mb-0017"
    
    static let BC_PREFIX =           "bc"
    static let BC_NAME_GENERATOR =   "bc-0001"
    
    static let IT_PREFIX =                    "it"
    static let IT_QUICK_WRITER =              "it-0001"
    static let IT_STOPWATCH =                 "it-0002"
    static let IT_DEVICE_INFO =               "it-0003"
    static let IT_QUICK_CALK =                "it-0004"
    static let IT_NUMBER_GENERATOR =          "it-0005"
    static let IT_NEXT_PAPER =                "it-0006"
    static let IT_CINEMA_SCOPE =              "it-0007"
    static let IT_WIFI_RATE =                 "it-0008"
    static let IT_TRY_SECRET =                "it-0009"
    static let IT_HERO_QUEST =                "it-0010"
    static let IT_LEARNING_CATS =             "it-0011"
    static let IT_ONE_MIN_TIMER =             "it-0012"
    static let IT_QR_GENERATOR =              "it-0013"
    static let IT_TIC_TAC_TOE =               "it-0014"
    static let IT_SNAKE =                     "it-0015"
    static let IT_CATCHER =                   "it-0016"
    
    static let VE_PREFIX =                    "ve"
    static let VE_QUIZ_BOOKS =                "ve-0001"
    static let VE_TYPES_OF_AIRCRAFT =         "ve-0002"
    static let VE_EVERY_DAY_FACTS =           "ve-0003"
    static let VE_FIND_UNIVERSITY =           "ve-0004"
    static let VE_PASS_GENERATOR =            "ve-0005"
    static let VE_NIGHT_BIRD =                "ve-0006"
    static let VE_QUIZ_VIDEOGAMES =           "ve-0007"
    static let VE_CHARGE_ME =                 "ve-0008"
    static let VE_FACTS_ABOUT_DOGS =          "ve-0009"
    static let VE_LUCKY_SPAN =                "ve-0010"
    static let VE_ALARM_MATERIAL =            "ve-0011"
    static let VE_CALENDAR_EVENTS =           "ve-0012"
    static let VE_ENGLISH_DICTIONARY_HELPER = "ve-0013"
    static let VE_RANDOM_DOGS =               "ve-0014"
    static let VE_VIGENERE_CHIPHER =          "ve-0015"
    static let VE_RECIPES_BOOK =              "ve-0016"
    static let VE_RANDOM_WORD_QUIZ =          "ve-0017"
    static let VE_SOUND_RECORDER =            "ve-0018"
    
    static let AK_PREFIX =                    "ak"
    static let AK_RICK_AND_MORTY =            "ak-0001"
    static let AK_SHASHLICK_CALCULATOR =      "ak-0002"
    static let AK_ALARM =                     "ak-0003"
    static let AK_TODO =                      "ak-0004"
    static let AK_BOILING_EGG =               "ak-0005"
    static let AK_COLOR_CONVERTER =           "ak-0006"
    static let AK_NEW_YEAR_COUNTDOWN =        "ak-0007"
    static let AK_UV_PROTECT =                "ak-0008"
    static let AK_RGB_CONVERTER =             "ak-0009"
    static let AK_RETROGRADE_MERCURY =        "ak-0010"
    static let AK_RANDOM_JOKE =               "ak-0011"
    static let AK_CARTOON_LOCATIONS =         "ak-0012"
    static let AK_FRUITS =                    "ak-0013"
    static let AK_POKER_CHANCES =             "ak-0014"
    static let AK_RANDOM_COFFEE =             "ak-0015"
    static let AK_CLICKER =                   "ak-0016"
    static let AK_DARTS =                     "ak-0017"
    static let AK_SPACE_ATTACKER =            "ak-0018"
    static let AK_QUIZ =                      "ak-0019"
    static let AK_MYTHOLOGY_QUIZ =            "ak-0020"
    static let AK_DODGER =                    "ak-0021"
    static let AK_FROG_CLICKER =              "ak-0022"
    static let AK_SPACE_ATTACKER_2 =          "ak-0023"
    
    static let KL_PREFIX =                    "kl"
    static let KL_BMI_CALCULATOR =            "kl-0001"
    static let KL_SPEED_TEST =                "kl-0002"
    static let KL_CONVERTER =                 "kl-0003"
    static let KL_RECORDER =                  "kl-0004"
    static let KL_CLICK_FASTER =              "kl-0005"
    static let KL_COLOR_SWATCHER =            "kl-0006"
    static let KL_DS_WEAPON =                 "kl-0007"
    static let KL_REACTION_TEST =             "kl-0008"
    static let KL_SUPERNATURAL_QUOTES =       "kl-0009"
    static let KL_TEA_WIKI =                  "kl-0010"
    static let KL_WEATHER_APP =               "kl-0011"
    static let KL_DOT_CROSS_GAME =            "kl-0012"
    static let KL_FLASHCARD_MAKER =           "kl-0013"
    static let KL_HIDDEN_PARIS =              "kl-0014"
    static let KL_BUBBLE_PICKER =             "kl-0015"
    static let KL_BODY_TYPE_CACLULATOR =      "kl-0016"
    static let KL_MOOD_TRACKER =              "kl-0017"
    static let KL_WORD_FINDER =               "kl-0018"
    static let KL_DODGER =                    "kl-0019"
    static let KL_STOPWATCH =                 "kl-0020"
    
    static let EG_PREFIX =                    "eg"
    static let EG_STOPWATCH =                 "eg-0001"
    static let EG_RACE =                      "eg-0002"
    static let EG_LUCKY_NUMBER =              "eg-0003"
    static let EG_PHONE_CHECKER =             "eg-0004"
    static let EG_DICE_ROLLER =               "eg-0005"
    static let EG_WATER_TRACKER =             "eg-0006"
    static let EG_CURRENCY_RATE =             "eg-0007"
    static let EG_LEARN_SLANG =               "eg-0008"
    static let EG_FLASHLIGHT =                "eg-0009"
    static let EG_EXPENSETRACKER =            "eg-0010"
    static let EG_WHICH_SPF =                 "eg-0011"
    static let EG_LOVE_CALCULATOR =           "eg-0012"
    static let EG_GET_LYRICS_GEN =            "eg-0013"
    static let EG_COCKTAIL_CRAFT =            "eg-0014"
    static let EG_PUZZLE_DIGITS =             "eg-0015"
    static let EG_TIC_TAC_TOE =               "eg-0016"
    static let EG_FLAPPY_BIRD =               "eg-0017"
    static let EG_JUMPER =                    "eg-0018"
    
    static let DT_PREFIX =                    "dt"
    static let DT_NUMBER_FACTS =              "dt-0001"
    static let DT_PROGRAMMING_JOKES =         "dt-0002"
    static let DT_QR_GEN_SHARE =              "dt-0003"
    static let DT_ROT13_ENCRYPT =             "dt-0004"
    static let DT_TEXT_SIMILARITY =           "dt-0005"
    static let DT_RIDDLE_REALM =              "dt-0006"
    static let DT_PASSWORD_GENERATOR =        "dt-0007"
    static let DT_NUTRITION_FINDER =          "dt-0008"
    static let DT_EMOJI_FINDER =              "dt-0009"
    static let DT_EASY_NOTES =                "dt-0010"
    static let DT_EXERCISE_FINDER =           "dt-0011"
    static let DT_PHONE_VALIDATOR =           "dt-0012"
    static let DT_HISTORICAL_EVENTS =         "dt-0013"
    static let DT_GASTRONOMY_GURU =           "dt-0014"
    static let DT_WORD_WISE =                 "dt-0015"
    static let DT_COCTAIL_FINDER =            "dt-0016"
    static let DT_POPULAR_MOVIES =            "dt-0017"
    static let DT_MUSIC_QUIZ =                "dt-0018"
    static let DT_LANGUAGE_IDENTIFIRE =       "dt-0019"
    
    static let KD_PREFIX =                   "kd"
    static let KD_GALLERY =                  "kd-0001"
    static let KD_NAME_GENERATOR =           "kd-0002"
    static let KD_NEWS =                     "kd-0003"
    static let KD_ASSATIATIONS =             "kd-0004"
    static let KD_FIND_UNIVERSITY =          "kd-0005"
    static let KD_CONVERTER =                "kd-0006"
    static let KD_CATS =                     "kd-0007"
    
    static let KD_PEDOMETER =                "kd-0008"
    
    static let KD_EXPENSE_TRACKER =          "kd-0010"
    
    
    static let EA_PREFIX =                   "ea"
    static let EA_REMINDER =                 "ea-0001"
    static let EA_TIMER =                    "ea-0002"
    
    static func checkSupportedProject(_ id: String) -> Bool {
        let unsupportedIds = [AppIDs.MB_CHECK_IP]
        if unsupportedIds.contains(id) {
            return false
        } else {
            return true
        }
    }
}
